### ISSUE TITLE
Exceeded Error Threshold on right_s1

### ISSUE THREAD

**Issue by arpit15** [RethinkRobotics/baxter_interface#81]
The joint_trajectory_action_server fails a lot of times when trying to replay a recorded trajectory and hangs after that.
` [ERROR] [WallTime: 1491592285.518791] /rsdk_position_w_id_joint_trajectory_action_server: Exceeded Error hmm Threshold on right_s1: `
I tried to track the source of error. It seems that the `self._command_stop(joint_names, self._limb.joint_angles(), start_time, dimensions_dict)` doesnot exit on line [276](https://github.com/RethinkRobotics/baxter_interface/blob/master/src/joint_trajectory_action/joint_trajectory_action.py#L276)
 I want to use server to keep moving forward in case it doesn't achieve the current joint state. However after this error everything stops. 
Kindly suggest what is a work around this issue as this occurs very frequently.
Thank you

**Comment by IanTheEngineer** [comment]
It seems you are starting the action server in `Position-controlled Inverse Dynamics` mode, which is likely not what you want in this context:

> [ERROR] [WallTime: 1491592285.518791] /rsdk_**position_w_id**_joint_trajectory_action_server: Exceeded Error hmm Threshold on right_s1:

 That mode is intended for more accurate feed-forward moves. If you're recording trajectories, you likely want `Velocity` mode, unless you are computing the Inverse dynamics velocities and accelerations:
http://sdk.rethinkrobotics.com/wiki/Joint_Trajectory_Playback_Example#Quickstart
`$ rosrun baxter_interface joint_trajectory_action_server.py --mode velocity`

**Comment by arpit15** [comment]
@IanTheEngineer I want to use a single server for task in which I command to go to a specific location using moveit and also execute pre-recorded trajectory. In case I use velocity mode, plan generated by moveit is not able to get me to the correct position. Is there a way to use them together in position control mode?

**Comment by IanTheEngineer** [comment]
Two control modes at the same time is not supported by the `JTAS`. To do this, you could either 
1) modify the `JTAS` to support accepting two control modes and switch between them dynamically
or
2) modify your code to compute the feed forward commands required to achieve the next position segment. That  means you'll supply the `JTAS` with the current desired joint position along with the velocity and acceleration calculation for the joint to reach the `n+1` position, rather than only the recorded joint positions. Without these extra commands, your action server will eventually start exceeding the thresholds set for error tracking.

**Comment by arpit15** [comment]
@IanTheEngineer If I record position, velocity and acceleration at the demo time and feed that to the jtas in position controlled inverse Dynamics mode, will that work?
Can you kindly tell me the method to calculate velocity and acceleration to feed in JTAS? I saw that in the limbs.py of baxter I could only get position, velocity and efforts. How could I get acceleration? Can I use the velocity finite difference for acceleration?
I tried to create 2 jtas servers with different with different publisher names and different parameter server. But the robot is not able to move smoothly with this setup. I guess JTAS might have some lock over the current joint configuration.

**Comment by arpit15** [comment]
I found a simpler solution [here](http://sdk.rethinkrobotics.com/wiki/Joint_Position_Example#playback-recordings). Thanks for all the help.
